on:
  push: 
   branches:
   - master_3.2.2
name: Start Deployment

jobs:
  deploy:
    name: Start Deployment
    runs-on: ubuntu-latest
    steps:
    - uses: TapTap21/docker-remote-deployment-action@v1.0
    - name: restar
      with:
        remote_docker_host: root@66.97.32.96 #ec2-user@ec2-34-246-134-80.eu-west-1.compute.amazonaws.com
        ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
        stack_file_name: docker-compose.yml
      #docker_login_password: ${{ secrets.DOCKER_REPO_PASSWORD }}
      #docker_login_user: ${{ secrets.DOCKER_REPO_USERNAME }}
      #docker_login_registry : ${{ steps.login-ecr.outputs.registry }}
        args: -p myapp up -d
