on: 
  push:
    branches:
    - master_3.2.2
#test    
name: deploy 

jobs:
  deploy: 
    name: deploy
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v1
    - name: build an d push to docker
      uses: docker/build-push-action@v1
      with: 
         username: ${{ secrets.DOCKERHUB_USERNAME }} 
         password: ${{ secrets.DOCKERHUB_PASSWORD }}
         repository: scanterra/geoserver_data
         tags: prueba-buildeo-develop

jobs:
  deploy:
    name: Start Deployment
    uses: TapTap21/docker-remote-deployment-action@v1.0
    with:
      remote_docker_host: root@66.97.32.96 #ec2-user@ec2-34-246-134-80.eu-west-1.compute.amazonaws.com
      ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
      ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
      stack_file_name: docker-compose.yml
      #docker_login_password: ${{ secrets.DOCKER_REPO_PASSWORD }}
      #docker_login_user: ${{ secrets.DOCKER_REPO_USERNAME }}
      #docker_login_registry : ${{ steps.login-ecr.outputs.registry }}
      args: -p myapp up -d
